version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mar1k1001
      POSTGRES_DB: uc_shop
    ports:
      - "5433:5432"